### ISSUE TITLE
Incorrect link to research paper

### ISSUE THREAD

**Issue by mabdullah1994** [harisbinzia/SimplifyUR#2]
Hi. It seems the link to the research paper is not correct. I tried accessing it and got redirected to the following link: 

http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.427.pdf

Could you please verify? Thanks!

**Comment by harisbinzia** [comment]
Hi, thanks for pointing it out. Updated the link.

http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.428.pdf
